BF.7.X:
  name: "BF.7.X (Omicron)"
  members:
    - "BF.7.X"
  # TODO please select new color!
  color: "#CBC3E3"

BA.4.6:
  name: "BA.4.6 (Omicron)"
  members:
    - "BA.4.6"
  color: "#CBC3E3"

BA.2.75:
  name: "BA.2.75 (Omicron)"
  members:
    - "BA.2.75"
  color: "#46196b" 
BA.5:
  name: "BA.5.X (Omicron)"
  members:
    - "BA.5.X"
  color: "#e21f26"

BA.4:
  name: "BA.4.X (Omicron)"
  members:
    - "BA.4.X"
  color: "#f57e20"

BA.2.12.X:
  name: "BA.2.12.X (Omicron)"
  members:
    - "BA.2.12.X"
  color: "#d0e6b5"

BA.2.X:
  name: "BA.2.X (Omicron)"
  members:
    - "BA.2.X"
  color: "#84bf40"

BA.1.1.X:
  name: "BA.1.1.X (Omicron)"
  members:
    - "BA.1.1.X"
  color: "#dbedf9"

BA.1:
  name: "BA.1 (Omicron)"
  members:
    - "BA.1"
  color: "#4aa3e0"

B.1.1.529:
  name: "B.1.1.529 (Omicron)"
  members:
    - "B.1.1.529"
  color: "#13496d"

Delta:
  name: "Delta"
  members:
    - "Delta"
  color: "#ffd576"

Other:
  name: "Other"
  members: null
  color: "#DDDDDD"
