name: growth rate calc

on:
  push:
    branches: [ "master" ]

jobs:
  testsuite:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup for conda
        uses: conda-incubator/setup-miniconda@v2
        with:        
          auto-update-conda: true
          channels: bioconda,conda-forge
          channel-priority: true
          python-version: 3.7
          activate-environment: test

      - name: Install
        shell: bash -l {0}
        run: |
          conda install -n base conda-libmamba-solver
          conda config --set solver libmamba
          conda config --add channels bioconda
          conda config --add channels conda-forge          
          conda install freyja pandas
          python calc_relgrowthrates.py

          # add and push changes
          if [[($(git status rel_growth_rates.csv --porcelain | wc -c) -ne 0)]]; then
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add rel_growth_rates.csv
          git commit -m "growth rate calc"
          git push origin master
          else
             echo "no change to growth rate estimate"
          fi;
